### ISSUE TITLE
Implement a generic zcl cluster command API 

### ISSUE THREAD

**Issue by wahajsyed** [chip-csg/connectedhomeip#38]
#### Problem
We currently implement each cluster command as a separate RPC, this approach is not scalable and we need to implement a generic cluster RPC

 #### Proposed Solution
Wrap the ZCL send command and expose it as an rpc that accepts the cluster, the command and command arguments as arguments to the RPC call.

**Comment by SaileeG** [comment]
Done: https://github.com/chip-csg/connectedhomeip/pull/43
